### ISSUE TITLE
Find and fix cases where WebDriver is bleeding into API space

### ISSUE THREAD

**Issue by mdittmer** [GoogleChromeLabs/confluence#292] opened 2018-05-15 01:28 UTC
A good starting point: several things in https://confluence-service-fix-dot-web-confluence.appspot.com/#!/catalog?releases=%5B%22Edge_16.16299_Windows_10.0%22,%22Safari_11.1_OSX_10.13.4%22,%22Chrome_66.0.3359.117_Windows_10.0%22,%22Firefox_60.0_Windows_10.0%22%5D&q=%22_%22

@kereliuk would you be able to take this on for ChromeDriver? I know @lukebjerring is already putting together a patch for one of the funky APIs in that list.

**Comment by kereliuk** [comment] 2018-05-15 12:11
I am confused what the issue is and how to interpret the link here. Can you provide more context? :)

**Comment by foolip** [comment] 2019-08-20 12:49
WebDriver itself doesn't add anything to the global object or anything else, and I haven't spotted any incorrect data that's because of the use of WebDriver to collect data, so closing this.

**Closed by foolip** 2019-08-20 12:49 UTC
Labels: backlog
