### ISSUE TITLE
Unit tests are broken

### ISSUE THREAD

**Issue by Hexcles** [GoogleChromeLabs/confluence#338] opened 2019-01-25 22:27 UTC
`npm run test` currently fails on master.

**Comment by foolip** [comment] 2019-02-06 11:15
I found this too, and also found that it's failing on the r2018-11-01_00 branch. Here's the interesting part of the output I think:
```
..Assertion failed: Axiom name conflict in org.chromium.apis.web.CompatClass : alpha1_2_3zulu9_8_7
F..Assertion failed: Object graph JSON file name expected to be of the form:
                      window_[browser-name]_[browser-version]_[platform-name][platform-version].json
F

Failures:
1) CompatClassGenerator should fail console.assert() validating with duplicate relases
  Message:
    Expected function to throw an exception.
  Stack:
    Error: Expected function to throw an exception.
        at UserContext.it (/usr/local/google/home/foolip/src/confluence/test/node/web_apis/api_compat_data-test.es6.js:29:14)

2) ApiExtractorService should throw when "environment" data is missing and filename is malformed
  Message:
    Expected function to throw an exception.
  Stack:
    Error: Expected function to throw an exception.
        at UserContext.it (/usr/local/google/home/foolip/src/confluence/test/node/web_catalog/api_extractor_service-test.es6.js:58:58)

Ran 125 of 133 specs
125 specs, 2 failures
Finished in 6.926 seconds
```

It's not clear if the "Assertion failed" bits at the beginning are the cause of the failure or not, seems like maybe it *didn't* throw an exception and that's why the test failed?

@mdittmer is it obvious what's wrong here?

**Comment by mdittmer** [comment] 2019-02-07 03:20
It's not obvious but your read is correct: we are asserting that we hit an
error condition but we are not hitting the expected error condition. The
error output prior to the test report is likely expected, but perhaps
something that used to throw is logging? Or perhaps some work is being
deferred so that no exception is synchronously thrown? These are just
guesses. I'd have to step through the particular tests to discover the
cause.

**Comment by foolip** [comment] 2019-02-07 09:37
It looks like both the test and the code under test was were added in https://github.com/GoogleChromeLabs/confluence/pull/253.

Oddly, the tests don't seem to fail on Travis:
https://travis-ci.org/GoogleChromeLabs/confluence/builds/489954534

The confluence branch of foam2 isn't set up on Travis, perhaps there's a connection.

**Comment by foolip** [comment] 2019-04-26 10:23
It looks like the failures are specific to Node.js 10:
https://github.com/GoogleChromeLabs/confluence/pull/358

The same tests were pass in https://github.com/GoogleChromeLabs/confluence/pull/357 with Node.js 8.

I'm running v10.15.3 locally so that explains some of what's happening.

**Comment by foolip** [comment] 2019-04-26 10:27
The assertion is from here:
https://github.com/foam-framework/foam2/blob/confluence/src/foam/core/debug.js#L166-L168

Why there's a difference between node 8 and 10 I don't know yet.

**Comment by foolip** [comment] 2019-04-26 10:39
https://travis-ci.org/GoogleChromeLabs/confluence/builds/524884969 demonstrates that it's actually the case that `foam.assert` throws on node8 and doesn't on node10. Intriguing...

**Comment by foolip** [comment] 2019-04-26 10:42
Alright, it's because of `console.assert`, as explained in https://developer.mozilla.org/en-US/docs/Web/API/console/assert: "Before Node.js v10.0.0, however, a falsy assertion would also cause an AssertionError to be thrown. This discrepancy was fixed with Node v10, so that console.assert() now acts the same in both Node and the browser."

**Comment by Hexcles** [comment] 2019-04-26 14:24
Aha! Compat issues! Who knew?

**Closed** 2019-04-26 15:01 UTC
Labels: bug

**Comment by foolip** [comment] 2019-04-26 15:12
And fixed by "UA sniffing", what could go wrong?
